POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email": "email1@email.com",
    "password": "password1!"
}

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email": "email2@email.com",
    "password": "password2!"
}

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "password1!",
    "role": "admin"
}